[package]
name = "medo"
version = "0.0.1"
authors = ["Sachin Cherian <sachinctl@protonmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
medo_core = { path = "..//core" }
medo_stacker = { path = "..//stacker" }
rayon = "1"
tracing = "0.1"
