[package]
name = "medo_stacker"
version = "0.0.1"
authors = ["Sachin Cherian <sachinctl@protonmail.com>"]
edition = "2021"
license = "MIT"
publish = false

[dependencies]
opencv = "0.66"
thiserror = "1"

tracing = "0.1"
