[package]
name = "medo_core"
version = "0.0.1"
authors = ["Sachin Cherian <sachinctl@protonmail.com>"]
edition = "2021"
license = "MIT"
publish = false

[dependencies]
lazy_static = "1"
opencv = "0.66"
thiserror = "1"
